"""add companion_memories table

Revision ID: 0821ef85caba
Revises: cb4d086d15ac
Create Date: 2026-09-13 00:59:29.296701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0821ef85caba'
down_revision: Union[str, Sequence[str], None] = 'cb4d086d15ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companion_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companion_memories_id'), 'companion_memories', ['id'], unique=False)
    op.create_index(op.f('ix_companion_memories_user_id'), 'companion_memories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companion_memories_user_id'), table_name='companion_memories')
    op.drop_index(op.f('ix_companion_memories_id'), table_name='companion_memories')
    op.drop_table('companion_memories')
    # ### end Alembic commands ###
