"""add_review_logs_table

Revision ID: 40d808e1abf5
Revises: 9b79233e4858
Create Date: 2026-09-19 22:40:21.452782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d808e1abf5'
down_revision: Union[str, Sequence[str], None] = '9b79233e4858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_logs', 'flashcard_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('review_logs_flashcard_id_fkey'), 'review_logs', type_='foreignkey')
    op.create_foreign_key(None, 'review_logs', 'flashcards', ['flashcard_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_logs', type_='foreignkey')
    op.create_foreign_key(op.f('review_logs_flashcard_id_fkey'), 'review_logs', 'flashcards', ['flashcard_id'], ['id'], ondelete='SET NULL')
    op.alter_column('review_logs', 'flashcard_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
