"""align document_id FK to ON DELETE SET NULL

Revision ID: cb4d086d15ac
Revises: a3b7f025ae69
Create Date: 2026-09-12 19:50:49.345409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4d086d15ac'
down_revision: Union[str, Sequence[str], None] = 'a3b7f025ae69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('flashcards_document_id_fkey'), 'flashcards', type_='foreignkey')
    op.create_foreign_key(None, 'flashcards', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flashcards', type_='foreignkey')
    op.create_foreign_key(op.f('flashcards_document_id_fkey'), 'flashcards', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
